[tool.briefcase]
project_name = "Keygen 3GS Offline"
bundle = "com.patch3gs.offline"
version = "1.0.0"
url = "https://3gspatch.com"
license = "MIT"
author = "Angga"
author_email = "admin@3gspatch.com"

[tool.briefcase.app.keygen3gs]
formal_name = "Keygen 3GS"
description = "Aplikasi Keygen PES 21 Offline"
long_description = "Aplikasi Keygen PES 21 Offline"
# Folder tempat kode python kita
sources = ["src/keygen3gs"]
test_sources = ["tests"]
# --- GANTI MENJADI INI (YANG BENAR) ---
requires = [
    "toga>=0.3.0",           # Library Tampilan (WAJIB ADA)
    "toga-android>=0.3.0"    # Library Khusus Android
]

[tool.briefcase.app.keygen3gs.macOS]
requires = ["std-nslog"]

[tool.briefcase.app.keygen3gs.linux]
requires = ["pygobject>=3.30"]

[tool.briefcase.app.keygen3gs.windows]
requires = []

[tool.briefcase.app.keygen3gs.android]
requires = ["toga-android>=0.3.0"]
